service:
  name: grg-serverless-todo-app

plugins:
  - serverless-iam-roles-per-function
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs12.x

  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}

  environment:
    TODOS_TABLE: Todos-${self:provider.stage}
    INDEX_NAME: grg-todo-id-idx

  iamRoleStatements:
    -
      Effect: Allow
      Resource: arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.TODOS_TABLE}
      Action:
        - dynamodb:Query
        - dynamodb:PutItem

package:
  individually: true

functions:
  GetTodos:
    handler: src/lambda/http/getTodos.handler
    events:
      -
        http:
          method: get
          path: todos
  CreateTodo:
    handler: src/lambda/http/createTodo.handler
    events:
      -
        http:
          method: post
          path: todos

resources:
  Resources:
    ServerlessTodoTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.TODOS_TABLE}
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          -
            AttributeName: userId
            AttributeType: S
          -
            AttributeName: createdAt
            AttributeType: S
          -
            AttributeName: todoId
            AttributeType: S
        KeySchema:
          -
            AttributeName: userId
            KeyType: HASH
          -
            AttributeName: createdAt
            KeyType: RANGE
        LocalSecondaryIndexes:
          -
            IndexName: ${self:provider.environment.INDEX_NAME}
            KeySchema:
              - 
                AttributeName: userId
                KeyType: HASH
              - 
                AttributeName: todoId
                KeyType: RANGE
            Projection:
              ProjectionType: ALL

        


    