service:
  name: grg-serverless-todo-app

custom:
  dynamodb:
    stages:
      - test
      - dev
    start:
      port: 8888
      inMemory: true
      migrate: true
  
  serverless-offline:
    httpPort: 3333

plugins:
  - serverless-iam-roles-per-function
  - serverless-webpack
  - serverless-offline
  - serverless-dynamodb-local

provider:
  name: aws
  runtime: nodejs12.x

  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}

  environment:
    TODOS_TABLE: Todos-${self:provider.stage}
    INDEX_NAME: userIdAndTodoIdIndex
    LOCAL_DATABASE_PORT: 8888
    LOCAL_DATABASE_ENDPOINT: http://localhost

  iamRoleStatements:
    -
      Effect: Allow
      Resource: arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.TODOS_TABLE}
      Action:
        - dynamodb:Query
        - dynamodb:PutItem
        - dynamodb:UpdateItem

package:
  individually: true

functions:
  GetTodos:
    handler: src/lambda/http/getTodos.handler
    events:
      -
        http:
          method: get
          path: todos
  CreateTodo:
    handler: src/lambda/http/createTodo.handler
    events:
      -
        http:
          method: post
          path: todos
  UpdateTodo:
    handler: src/lambda/http/updateTodo.handler
    events:
      -
        http:
          method: patch
          path: todos/{todoId}
          

resources:
  Resources:
    ServerlessTodoTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.TODOS_TABLE}
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          -
            AttributeName: userId
            AttributeType: S
          -
            AttributeName: createdAt
            AttributeType: S
          -
            AttributeName: todoId
            AttributeType: S
        KeySchema:
          -
            AttributeName: userId
            KeyType: HASH
          -
            AttributeName: createdAt
            KeyType: RANGE
        LocalSecondaryIndexes:
          -
            IndexName: ${self:provider.environment.INDEX_NAME}
            KeySchema:
              - 
                AttributeName: userId
                KeyType: HASH
              - 
                AttributeName: todoId
                KeyType: RANGE
            Projection:
              ProjectionType: ALL

        


    